# -*- coding: utf-8 -*-
"""PDFtoAudiobookConverter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j3zanQ5QxX4oC98dIcLHWuHRKIrAFgIl
"""

!pip install PyPDF2 gTTS
!pip install gtts --upgrade
!pip install gtts-token --upgrade

import PyPDF2
from gtts import gTTS
import re
import os

# Open the PDF file
with open('nobsselfhelp', 'rb') as pdf_file:
    pdf_reader = PyPDF2.PdfReader(pdf_file)

    # Initialize variables to track chapter start
    chapter_marker = re.compile(r'Chapter [0-9]+')  # Customize the pattern for your PDF
    text = ''
    chapters = []

    # Read each page and extract text
    for page_num in range(len(pdf_reader.pages)):
        page = pdf_reader.pages[page_num]
        page_text = page.extract_text()
        text += page_text

        # Check if the current page contains a chapter marker
        if chapter_marker.search(page_text):
            chapters.append(page_text)

# Create a directory to store chapter MP3 files
os.makedirs('chapter_mp3', exist_ok=True)

# Function to generate a valid filename within a character limit
def generate_valid_filename(chapter_number, chapter_title, max_length=100):
    # Remove invalid characters and limit the length
    cleaned_title = re.sub(r'[\/:*?"<>|]', '_', chapter_title.strip())
    if len(cleaned_title) > max_length:
        cleaned_title = cleaned_title[:max_length]
    return f'book_chapter_{chapter_number}_{cleaned_title}.mp3'

# Convert each chapter to speech and save as separate MP3 files
for chapter_number, chapter_text in enumerate(chapters, start=1):
    # Generate a valid filename
    chapter_filename = generate_valid_filename(chapter_number, chapter_text)

    # Convert text to speech with custom parameters (e.g., language and speech rate)
    tts = gTTS(chapter_text, lang='en', slow=True)

    # Save the audio as a separate MP3 file in the 'chapter_mp3' directory
    tts.save(os.path.join('chapter_mp3', chapter_filename))

# Import necessary libraries
import PyPDF2
from gtts import gTTS

# Open the PDF file
with open('nobsselfhelp', 'rb') as pdf_file:
    pdf_reader = PyPDF2.PdfReader(pdf_file)

    # Initialize an empty string to store text
    text = ''

    # Read each page and extract text
    for page_num in range(len(pdf_reader.pages)):
        page = pdf_reader.pages[page_num]
        text += page.extract_text()

# Convert text to speech
tts = gTTS(text)

# Save the audio to a file
tts.save('nobsselfhelp2.mp3')